// swift-tools-version:5.5
// this file is automatically generated with SourceGear Bridge
import PackageDescription
let package = Package(
    name : "sourcegear-bridge-dotnet",
	platforms: [.macOS(.v12)],
    products : [
        .library(
            name : "dotnet",
            targets : [
                "dotnet",
            ]
            ),
    ],
    dependencies : [
        .package(name: "sourcegear-bridge-lib-hook", url: "https://github.com/sourcegear/sourcegear-bridge-lib-hook", .exact("0.2.0")),
    ],
    targets : [
        .target(
            name: "jumptable_dotnet",
            dependencies : [
                .product(name: "sg_resolve_jumptable", package: "sourcegear-bridge-lib-hook"),
            ],
            path: "C/dotnet"
            ),
        .target(
            name: "dotnet",
            dependencies : [
                .target(name: "jumptable_dotnet"),
            ],
			swiftSettings: [
				.unsafeFlags([
					"-Xfrontend", "-enable-experimental-concurrency",
					"-Xfrontend", "-disable-availability-checking",
				])
			],
            path: "Sources/dotnet"
            ),
    ]
)
